using System.ComponentModel;
using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.Json;
using ModelContextProtocol.Server;
using PixMcp.Pix;

namespace PixMcp;

/// <summary>
/// Generates docs/tools.md from the registered tools: title, annotations, toolset, static cost, description, parameters
/// (type, default, enum values, bounds, description), top-level output fields, and the error codes. Program.cs runs it for
/// <c>--tool-reference PATH [--check]</c>; --check exits 2 when PATH is missing or stale, 1 on a usage error.
/// </summary>
internal static class ToolReference
{
    internal static int Run(string[] args, TextWriter output, TextWriter error)
    {
        string[] paths = args.Where(a => !a.StartsWith("--", StringComparison.Ordinal)).ToArray();
        bool check = args.Contains("--check");
        if (paths.Length != 1 || args.Any(a => a.StartsWith("--", StringComparison.Ordinal) && a != "--check"))
        {
            error.WriteLine("pixmcp: usage: PixMcp.exe --tool-reference PATH [--check]");
            return 1;
        }
        string path = ServerPaths.Full(paths[0]);
        string generated = Generate();
        if (check)
        {
            string? existing = File.Exists(path) ? File.ReadAllText(path).ReplaceLineEndings("\n") : null;
            if (existing == generated)
            {
                output.WriteLine($"pixmcp: {paths[0]} is current");
                return 0;
            }
            error.WriteLine($"pixmcp: {paths[0]} is {(existing is null ? "missing" : "stale")}; regenerate with PixMcp.exe --tool-reference {paths[0]}");
            return 2;
        }
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, generated);
        output.WriteLine($"pixmcp: wrote {paths[0]}");
        return 0;
    }

    internal static string Generate()
    {
        (MethodInfo Method, McpServerToolAttribute Attribute)[] tools = typeof(ServerHost).Assembly.GetTypes()
            .SelectMany(t => t.GetMethods(BindingFlags.Public | BindingFlags.Static))
            .Select(m => (Method: m, Attribute: m.GetCustomAttribute<McpServerToolAttribute>()!))
            .Where(t => t.Attribute?.Name is not null)
            .OrderBy(t => t.Attribute.Name, StringComparer.Ordinal).ToArray();
        IGrouping<string, (MethodInfo Method, McpServerToolAttribute Attribute)>[] toolsets = tools
            .GroupBy(t => Toolsets.For(t.Attribute.Name!) ?? "unassigned").OrderBy(g => g.Key, StringComparer.Ordinal).ToArray();

        var text = new StringBuilder();
        text.Append("# pixmcp tool reference\n\n");
        text.Append($"Generated by `PixMcp.exe --tool-reference docs/tools.md` from the {tools.Length} registered tools; do not edit by hand. ");
        text.Append("Costs are the static hints `nextCalls` carry (`cached`, `query`, `replay`, `pixtool`, `job`); a replay tool answers ");
        text.Append("from memory once its preparation exists. `PIXMCP_TOOLSETS` enables toolsets; `session` is always on.\n\n");
        text.Append("| Toolset | Tools |\n|---|---|\n");
        foreach (var toolset in toolsets)
            text.Append($"| `{toolset.Key}` | {string.Join(", ", toolset.Select(t => $"[`{t.Attribute.Name}`](#{t.Attribute.Name})"))} |\n");
        foreach (var toolset in toolsets)
        {
            text.Append($"\n## {toolset.Key}\n");
            foreach ((MethodInfo method, McpServerToolAttribute attribute) in toolset)
                AppendTool(text, method, attribute);
        }
        AppendErrorCodes(text);
        return text.ToString();
    }

    private static void AppendTool(StringBuilder text, MethodInfo method, McpServerToolAttribute attribute)
    {
        string name = attribute.Name!;
        var annotations = new List<string>();
        if (attribute.ReadOnly) annotations.Add("read-only");
        if (attribute.Destructive) annotations.Add("destructive");
        if (attribute.Idempotent) annotations.Add("idempotent");
        if (attribute.OpenWorld) annotations.Add("open-world");
        text.Append($"\n### {name}\n\n");
        text.Append($"**{attribute.Title ?? name}** · {(annotations.Count == 0 ? "no annotations" : string.Join(", ", annotations))} · cost `{CostHints.Default(name)}`\n\n");
        text.Append((method.GetCustomAttribute<DescriptionAttribute>()?.Description ?? "").ReplaceLineEndings(" ")).Append("\n\n");

        ParameterInfo[] parameters = method.GetParameters().Where(p => !Injected(p.ParameterType)).ToArray();
        if (parameters.Length == 0)
        {
            text.Append("No parameters.\n");
        }
        else
        {
            text.Append("| Parameter | Type | Default | Description |\n|---|---|---|---|\n");
            foreach (ParameterInfo parameter in parameters)
            {
                string parameterName = parameter.Name!;
                var notes = new List<string> { parameter.GetCustomAttribute<DescriptionAttribute>()?.Description ?? "" };
                if (StructuredToolResults.Choices(name, parameterName) is string[] choices)
                    notes.Add("One of " + string.Join(", ", choices.Select(c => $"`{c}`")) + ".");
                (double? min, double? max) = StructuredToolResults.Bounds(name, parameterName);
                if (min is not null || max is not null)
                    notes.Add($"Range {Number(min)}..{Number(max)}.");
                text.Append($"| `{parameterName}` | {TypeName(parameter.ParameterType)} | {DefaultValue(parameter)} | {Cell(string.Join(" ", notes.Where(n => n.Length > 0)))} |\n");
            }
        }
        string fields = OutputFields(name);
        if (fields.Length > 0)
            text.Append($"\nOutput: {fields}\n");
    }

    private static void AppendErrorCodes(StringBuilder text)
    {
        text.Append("\n## Error codes\n\nErrors carry `code`, `message`, `retryable` and executable `nextCalls`.\n\n| Code | Retryable |\n|---|---|\n");
        IEnumerable<string> codes = typeof(PixErrors.Codes).GetFields(BindingFlags.Public | BindingFlags.Static)
            .Where(f => f.IsLiteral && f.FieldType == typeof(string)).Select(f => (string)f.GetRawConstantValue()!)
            .Distinct().Order(StringComparer.Ordinal);
        foreach (string code in codes)
            text.Append($"| `{code}` | {(PixErrors.Codes.Retryable.Contains(code) ? "yes" : "no")} |\n");
    }

    /// <summary>Services the host injects rather than the client supplies.</summary>
    private static bool Injected(Type type)
        => type == typeof(PixSession) || type == typeof(JobManager) || type == typeof(CancellationToken)
            || type.Namespace?.StartsWith("ModelContextProtocol", StringComparison.Ordinal) == true
            || type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IProgress<>);

    private static string TypeName(Type type)
    {
        if (Nullable.GetUnderlyingType(type) is Type underlying) return TypeName(underlying);
        if (type == typeof(string) || type.IsEnum) return "string";
        if (type == typeof(bool)) return "boolean";
        if (type == typeof(int) || type == typeof(long) || type == typeof(uint) || type == typeof(ulong) || type == typeof(short) || type == typeof(byte)) return "integer";
        if (type == typeof(double) || type == typeof(float) || type == typeof(decimal)) return "number";
        if (type == typeof(JsonElement)) return "any";
        if (type.IsArray) return TypeName(type.GetElementType()!) + "[]";
        if (type.IsGenericType)
        {
            Type[] arguments = type.GetGenericArguments();
            if (arguments.Length == 2 && type.GetInterfaces().Append(type).Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>)))
                return $"object of {TypeName(arguments[1])}";
            if (arguments.Length == 1 && typeof(System.Collections.IEnumerable).IsAssignableFrom(type))
                return TypeName(arguments[0]) + "[]";
        }
        return type.Name;
    }

    private static string DefaultValue(ParameterInfo parameter)
    {
        if (!parameter.HasDefaultValue) return "required";
        return parameter.DefaultValue switch
        {
            null => "`null`",
            string s => $"`\"{s}\"`",
            bool b => b ? "`true`" : "`false`",
            IFormattable number => $"`{number.ToString(null, CultureInfo.InvariantCulture)}`",
            object other => $"`{other}`",
        };
    }

    private static string Number(double? value) => value?.ToString(CultureInfo.InvariantCulture) ?? "";

    private static string Cell(string value) => value.ReplaceLineEndings(" ").Replace("|", "\\|", StringComparison.Ordinal);

    /// <summary>Top-level fields of the output schema; alternatives (anyOf) are listed separately.</summary>
    private static string OutputFields(string tool)
    {
        var alternatives = new List<string>();
        void Collect(JsonElement element)
        {
            if (element.ValueKind != JsonValueKind.Object) return;
            if (element.TryGetProperty("anyOf", out JsonElement anyOf))
            {
                foreach (JsonElement item in anyOf.EnumerateArray()) Collect(item);
                return;
            }
            if (element.TryGetProperty("properties", out JsonElement properties))
                alternatives.Add(string.Join(", ", properties.EnumerateObject().Select(p => $"`{p.Name}`")));
        }
        Collect(StructuredToolResults.SchemaFor(tool));
        return string.Join(" | or | ", alternatives.Where(a => a.Length > 0).Distinct());
    }
}
